packages:
  - "apps/*"
  - "packages/*"
  - "tooling/*"

catalog:
  typescript: ^5.7.2
  tsup: ^8.2.4
  prettier: ^3.4.2
  "@biomejs/biome": ^1.9.4
  typedoc: "^0.27.6"

catalogs:
  vitejs:
    vite: ^6.0.11
    vite-tsconfig-paths: ^5.1.4
    vitest: ^3.0.4
    jsdom: ^26.0.0
